# Generated by Django 5.1.3 on 2024-11-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_profile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_link',
        ),
        migrations.AddField(
            model_name='profile',
            name='git',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkdn',
            field=models.URLField(blank=True, null=True),
        ),
    ]
