# Generated by Django 5.1.3 on 2024-11-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0003_remove_profile_social_link_profile_git_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('alumni', 'Alumni'), ('student', 'Mentor')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
