# Generated by Django 5.1.3 on 2024-12-02 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0004_user_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
