# Generated by Django 5.1.3 on 2024-12-02 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_liked_by_alter_like_post_alter_like_user'),
        ('userauths', '0005_profile_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='saved',
            field=models.ManyToManyField(blank=True, related_name='saved_posts', to='post.post'),
        ),
    ]
