# Generated by Django 5.1.3 on 2024-12-21 04:33

import userauths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0006_alter_profile_saved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='images/default.jpg', null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
