# Generated by Django 5.1.3 on 2025-02-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('Alumni', 'Alumni'), ('Student', 'Student')], max_length=20),
        ),
    ]
