# Generated by Django 5.1.3 on 2025-02-23 14:48

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0012_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
