# Generated by Django 5.1.3 on 2025-03-16 15:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0013_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='images/default.jpg', max_length=255, null=True, verbose_name='image'),
        ),
    ]
