# Generated by Django 5.1.3 on 2024-12-09 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
