# Generated by Django 5.1.3 on 2025-03-17 04:49

import post.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='file.jpg', null=True, upload_to=post.models.user_directory_path, verbose_name='Post Image'),
        ),
    ]
