# Generated by Django 5.1.3 on 2025-03-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(default='file.jpg', null=True, upload_to='', verbose_name='Profile_pic'),
        ),
    ]
