# Generated by Django 5.1.3 on 2025-02-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_rename_time_stamp_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('save', 'Save'), ('message', 'Message'), ('comment', 'Comment')], max_length=10),
        ),
    ]
