# Generated by Django 5.1.3 on 2025-02-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('message', 'Message'), ('comment', 'Comment'), ('follow', 'Follow')], max_length=10),
        ),
    ]
