# Generated by Django 5.1.3 on 2024-12-23 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='author',
            new_name='user',
        ),
    ]
