# Generated by Django 5.1.3 on 2024-12-24 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_author_groupmessage_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmessage',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
